package com.purchasing.agent;
import com.purchasing.dto.ReviewRequest; import com.purchasing.dto.ReviewResponse; import com.purchasing.dto.ReviewResponse.Factor; import com.purchasing.entity.*; import com.purchasing.repository.RecommendationRepository; import com.purchasing.service.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.*; import java.util.*;
@Service public class PurchasingAgent {
  final RecommendationRepository recommendations; final PurchasingTools tools; final PurchaseOrderService poService;
  public PurchasingAgent(RecommendationRepository r,PurchasingTools t,PurchaseOrderService p){recommendations=r;tools=t;poService=p;}
  @Transactional public ReviewResponse review(Long id){ return review(id,null); }
  @Transactional public ReviewResponse review(Long id, ReviewRequest input){
    PurchaseRecommendation rec=recommendations.findById(id).orElseThrow(()->new NoSuchElementException("Recommendation not found")); Product p=rec.product; Supplier s=tools.getSupplierInformation(rec.supplier);
    int onHand=value(input==null?null:input.currentInventory(),tools.getProductInventory(p)), demand=value(input==null?null:input.expectedDemand(),tools.getExpectedDemand(p)), open=value(input==null?null:input.openPurchaseOrders(),tools.getOpenPurchaseOrders(p)), storage=value(input==null?null:input.availableStorageCapacity(),tools.getStorageCapacity(p)), leadTime=value(input==null?null:input.supplierLeadTimeDays(),s.leadTimeDays), minimumOrder=value(input==null?null:input.supplierMinimumOrderQuantity(),s.minimumOrderQuantity), horizon=value(input==null?null:input.forecastHorizonDays(),30); BigDecimal budget=input!=null&&input.availableBudget()!=null?input.availableBudget():tools.getBudget(), daily=input!=null&&input.averageDailyConsumption()!=null?input.averageDailyConsumption():BigDecimal.valueOf(demand).divide(BigDecimal.valueOf(Math.max(1,horizon)),2,RoundingMode.HALF_UP); int consumptionDemand=daily.multiply(BigDecimal.valueOf(horizon)).setScale(0,RoundingMode.HALF_UP).intValue(), needed=Math.max(0,demand-onHand-open), maxStorage=Math.max(0,storage-onHand-open), maxBudget=budget.divide(p.unitCost,0,RoundingMode.DOWN).intValue(), feasible=Math.min(Math.min(maxStorage,maxBudget),s.availableQuantity);
    List<Factor> f=new ArrayList<>(); f.add(new Factor("Forecast demand","POSITIVE","Buyer forecast is "+demand+" units for the next "+horizon+" days; inventory and inbound POs leave a net requirement of "+needed+" units.")); f.add(new Factor("Consumption trend","NEUTRAL","Average consumption of "+daily+" units/day projects "+consumptionDemand+" units over "+horizon+" days. The stated forecast remains the ordering baseline.")); f.add(new Factor("Open Purchase Orders","NEUTRAL",open+" units are already inbound and were deducted before deciding.")); f.add(new Factor("Supplier constraints","NEUTRAL",s.name+" has a "+leadTime+" day lead time and MOQ of "+minimumOrder+" units.")); f.add(new Factor("Budget","NEUTRAL","$"+budget+" supports up to "+maxBudget+" units at $"+p.unitCost+" each.")); f.add(new Factor("Storage","NEUTRAL","Capacity allows "+maxStorage+" additional units after on-hand and inbound stock."));
    if(needed==0) return result("REJECTED",rec.quantity,0,.96,"No incremental purchase is required after inventory and inbound orders.",f,null,List.of(),"No action taken",false);
    if(feasible<minimumOrder) return result("INVESTIGATED_FURTHER",rec.quantity,0,.72,"A purchase is needed, but no quantity can meet MOQ while staying within budget and storage.",f,null,List.of("Human approval required"),"Escalated to buyer",true);
    int target=Math.min(needed,feasible); if(target<minimumOrder) target=minimumOrder; target=Math.min(target,feasible); if(target<minimumOrder) return result("INVESTIGATED_FURTHER",rec.quantity,0,.70,"Constraint conflict requires buyer review.",f,null,List.of("MOQ conflict"),"Escalated to buyer",true);
    String decision=target==rec.quantity?"ACCEPTED":"MODIFIED"; String summary=decision.equals("ACCEPTED")?"The recommendation meets demand, supplier, budget, and storage constraints.":"The recommendation was adjusted to "+target+" units to avoid over-ordering while covering the forecast.";
    PurchaseOrder po=poService.create(p,s,target); Map<String,Object> validation=poService.validate(po,budget,storage,onHand,open,minimumOrder); @SuppressWarnings("unchecked") List<String> issues=(List<String>)validation.get("issues");
    if(Boolean.FALSE.equals(validation.get("valid"))){ po.status="REVIEW_REQUIRED"; return result("INVESTIGATED_FURTHER",rec.quantity,target,.68,"The created PO failed validation and was routed for human review.",f,po,issues,"Validation failed; PO marked REVIEW_REQUIRED",true); }
    return result(decision,rec.quantity,target,decision.equals("ACCEPTED")?.94:.91,summary,f,po,issues,"PO created and validated",false);
  }
  private int value(Integer supplied,int fallback){return supplied==null?fallback:supplied;}
  private ReviewResponse result(String d,int original,int q,double c,String summary,List<Factor> f,PurchaseOrder po,List<String> issues,String recovery,boolean approval){
    List<String> recommendations=switch(d){case "ACCEPTED"->List.of("Release the validated purchase order and monitor delivery against the supplier lead time.","Re-check the demand forecast before the next replenishment cycle.");case "MODIFIED"->List.of("Proceed with the adjusted quantity of "+q+" units instead of the system's "+original+" units.","Do not release the remaining "+Math.max(0,original-q)+" units without a new demand or capacity review.");case "REJECTED"->List.of("Do not create a purchase order now; current and inbound stock already cover the stated forecast.","Review the recommendation again when the forecast changes or inbound POs are delayed.");default->List.of("Do not release a PO automatically. Ask the buyer to resolve the budget, MOQ, or storage conflict.","Consider a different supplier, more storage, or a revised forecast before ordering.");};
    List<String> checks=po==null?List.of("No PO validation was run because the agent did not create an order."):issues.isEmpty()?List.of("Quantity is positive.","Supplier MOQ is satisfied.","Cost is within the buyer-provided budget.","Resulting inventory fits the buyer-provided storage capacity.","Supplier and product details are valid."):issues;
    String evaluation="The agent compared the fixed 800-unit system recommendation against the buyer-provided demand, inventory, inbound PO, supplier, budget, and storage constraints before selecting this outcome.";
    return new ReviewResponse(d,original,q,c,summary,f,po!=null,po==null?null:po.id,po==null?null:po.status,po==null?"NOT_APPLICABLE":"PASSED",issues,recovery,approval,evaluation,recommendations,checks);
  }
}
